# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.
[tools]
rojo = "rojo-rbx/rojo@7.7.0"
lune = "lune-org/lune@0.10.4"
luau-lsp = "johnnymorganz/luau-lsp@1.24.1"
stylua = "johnnymorganz/stylua@2.3.0"
selene = "Kampfkarren/selene@0.29.0"
